name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide_border=true&include_all_commits=true&rank_icon=percentile&exclude_repo=mimotion&theme=github_dark
          path: profile/stats_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate stats card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide_border=true&include_all_commits=true&rank_icon=percentile&exclude_repo=mimotion&theme=default
          path: profile/stats_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&hide_border=true&theme=github_dark
          path: profile/top-langs_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&hide_border=true&theme=default
          path: profile/top-langs_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Desktop Schedule
      - name: Generate desktop-schedule card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=desktop-schedule&hide_border=true&theme=github_dark
          path: profile/pinned-desktop-schedule_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate desktop-schedule card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=desktop-schedule&hide_border=true&theme=default
          path: profile/pinned-desktop-schedule_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # GitScratch Frontend (UniScratch Organization)
      - name: Generate gitscratch-frontend card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=UniScratch&repo=gitscratch-frontend&hide_border=true&theme=github_dark
          path: profile/pinned-gitscratch-frontend_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gitscratch-frontend card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=UniScratch&repo=gitscratch-frontend&hide_border=true&theme=default
          path: profile/pinned-gitscratch-frontend_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # GitScratch Backend (UniScratch Organization)
      - name: Generate gitscratch-backend-flask card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=UniScratch&repo=gitscratch-backend-flask&hide_border=true&theme=github_dark
          path: profile/pinned-gitscratch-backend-flask_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gitscratch-backend-flask card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=UniScratch&repo=gitscratch-backend-flask&hide_border=true&theme=default
          path: profile/pinned-gitscratch-backend-flask_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Mine Genshin
      - name: Generate mine-genshin card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=mine-genshin&hide_border=true&theme=github_dark
          path: profile/pinned-mine-genshin_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate mine-genshin card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=mine-genshin&hide_border=true&theme=default
          path: profile/pinned-mine-genshin_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Rainmeter QWeather Widget
      - name: Generate rainmeter-qweather-widget card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=rainmeter-qweather-widget&hide_border=true&theme=github_dark
          path: profile/pinned-rainmeter-qweather-widget_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate rainmeter-qweather-widget card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=rainmeter-qweather-widget&hide_border=true&theme=default
          path: profile/pinned-rainmeter-qweather-widget_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Personal Blog
      - name: Generate timfang4162.github.io card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=timfang4162.github.io&hide_border=true&theme=github_dark
          path: profile/pinned-timfang4162-github-io_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timfang4162.github.io card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=timfang4162.github.io&hide_border=true&theme=default
          path: profile/pinned-timfang4162-github-io_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # NextBot
      - name: Generate NextBot card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=NextBot&hide_border=true&theme=github_dark
          path: profile/pinned-NextBot_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate NextBot card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=NextBot&hide_border=true&theme=default
          path: profile/pinned-NextBot_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # MicroPython NV3007
      - name: Generate micropython-nv3007 card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=micropython_nv3007&hide_border=true&theme=github_dark
          path: profile/pinned-micropython-nv3007_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate micropython-nv3007 card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=micropython_nv3007&hide_border=true&theme=default
          path: profile/pinned-micropython-nv3007_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
